apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-6qgx
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-6qgx@sha256:4beabd71466c301c2de29d38f659a4c5cb1a231d7dee1ae17aeea4f82814e091
        name: my-nodejs
        resources: {}
status: {}
